package bwie.com.myfate.databases;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bwie.com.myfate.bean.NearbyDataBean;

import bwie.com.myfate.databases.NearbyDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nearbyDataBeanDaoConfig;

    private final NearbyDataBeanDao nearbyDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nearbyDataBeanDaoConfig = daoConfigMap.get(NearbyDataBeanDao.class).clone();
        nearbyDataBeanDaoConfig.initIdentityScope(type);

        nearbyDataBeanDao = new NearbyDataBeanDao(nearbyDataBeanDaoConfig, this);

        registerDao(NearbyDataBean.class, nearbyDataBeanDao);
    }
    
    public void clear() {
        nearbyDataBeanDaoConfig.clearIdentityScope();
    }

    public NearbyDataBeanDao getNearbyDataBeanDao() {
        return nearbyDataBeanDao;
    }

}
